import Tabs, { Tab } from "@/components/tabs";
import { useWallet } from "@/context/wallet";
import { head } from "lodash";
import { WithRouterProps } from "next/dist/client/with-router";
import Head from "next/head";
import Router from "next/router";
import { useEffect } from "react";
import { LoaderIcon } from "react-hot-toast";
import { FetchStatus } from "../home";

interface PageProps extends WithRouterProps {}

const OrdinalsPage: React.FC<PageProps> = ({ router }) => {
  const {
    changeAddress,
    artifacts,
    getArtifacts,
    fetchArtifactsStatus,
    setFetchArtifactsStatus,
    payPk,
    ordPk,
  } = useWallet();

  useEffect(() => {
    const fire = async (a: string) => {
      await getArtifacts(a);
      // const ordinalUtxos = await getOrdinalUTXOs(a);
    };
    if (changeAddress && fetchArtifactsStatus === FetchStatus.Idle) {
      fire(changeAddress);
    }
  }, [getArtifacts, fetchArtifactsStatus, changeAddress]);

  return (
    <>
      <Head>
        <title>1SatOrdinals.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono&family=Roboto+Slab&family=Ubuntu:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Tabs currentTab={Tab.Ordinals} />

      <div>
        {fetchArtifactsStatus !== FetchStatus.Loading && (
          <div
            className="text-sm text-center mx-auto cursor-pointer text-blue-500 hover:text-blue-400"
            onClick={() => setFetchArtifactsStatus(FetchStatus.Idle)}
          >
            Refresh
          </div>
        )}

        {fetchArtifactsStatus === FetchStatus.Loading && (
          <div className="w-full my-12 max-w-4xl mx-auto text-center">
            <LoaderIcon className="mx-auto" />
          </div>
        )}

        {fetchArtifactsStatus !== FetchStatus.Loading && (!payPk || !ordPk) && (
          <div
            className="max-w-md rounded my-8 bg-[#222] hover:bg-[#333] cursor-pointer mx-auto p-8"
            onClick={() => Router.push("./wallet")}
          >
            You need a wallet first.
          </div>
        )}
        {fetchArtifactsStatus === FetchStatus.Success &&
          artifacts?.length === 0 &&
          payPk &&
          ordPk && (
            <div className="max-w-md rounded bg-[#222] hover:bg-[#333] cursor-pointer mx-auto p-8 my-8">
              You, sadly, have no artifacts.
            </div>
          )}

        <div className="w-full my-12 grid grid-cols-2 gap-4 md:grid-cols-4 max-w-4xl mx-auto">
          {artifacts?.map((a) => {
            return (
              <a
                key={a.outPoint}
                target="_blank"
                href={`https://whatsonchain.com/tx/${head(
                  a.outPoint.split("_")
                )}`}
              >
                <img
                  className="w-full rounded"
                  // src={`https://ordinals.gorillapool.io/api/origin/${
                  //   a.outPoint.split("_")[0]
                  // }/${a.outPoint.split("_")[1]}`}
                  src={`data:${a.contentType};base64,${a.dataB64}`}
                />
              </a>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default OrdinalsPage;
