[phases.setup]
    # https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
    nixpkgsArchive = 'd4af44bfa3317ea03607f8d9eba19fab6bd7634d' # https://github.com/NixOS/nixpkgs/commit/d4af44bfa3317ea03607f8d9eba19fab6bd7634d