[phases.setup]
    # https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
    nixpkgsArchive = '0d1ef1a839ce0f3282bf24bea2788b9ad659be83' # https://github.com/NixOS/nixpkgs/commit/0d1ef1a839ce0f3282bf24bea2788b9ad659be83