import oneSatLogo from "@/assets/images/icon.svg";
import Inscribe from "@/components/inscriptions/inscribe";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import router from "next/router";
import { useMemo, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  const [showInscribe, setShowInscribe] = useState<boolean>(false);
  const [rawTx, setRawTx] = useState<string | undefined>(undefined);

  const content = useMemo(() => {
    return (
      <div
        className="h-full w-full flex flex-col items-center justify-center max-w-[600px]"
        style={{
          color: "yellow",
          fontFamily: "monospace",
        }}
      >
        {!showInscribe && (
          <div className="cursor-pointer my-8 w-full">
            <Image
              style={{
                boxShadow: "0 0 0 0 rgba(0, 0, 0, 1)",
                transform: "scale(1)",
                animation: "pulse 2s infinite",
                width: "12rem",
                height: "12rem",
              }}
              src={oneSatLogo}
              onClick={() => setShowInscribe(true)}
              alt={"1Sat Ordinals"}
              className="mx-auto"
            />
          </div>
        )}
        {showInscribe && <Inscribe callback={(hex) => setRawTx(hex)} />}
      </div>
    );
  }, [showInscribe]);

  return (
    <>
      <Head>
        <title>1SatOrdinals.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono&family=Roboto+Slab&family=Ubuntu:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="flex items-center justify-center h-screen w-screen">
        <div className="flex flex-col items-center justify-between w-full h-full">
          <div className="h-10">
            <h1
              className="text-2xl my-4 cursor-pointer"
              onClick={() => router.push("/")}
            >
              1Sat Ordinals
            </h1>
          </div>
          {!rawTx ? (
            content
          ) : (
            <div>
              <div className="text-center">Ordinal Created</div>
              <div className="w-[600px] w-full p-2 h-[400px] whitespace-pre-wrap break-all overflow-auto rounded bg-[#111] text-sm p-2 text-[#aaa]">
                {rawTx}
              </div>
              <div>
                <button
                  onClick={() => alert("soonTm")}
                  className="w-full p-2 text-lg bg-green-400 rounded my-4 text-black font-semibold"
                >
                  Broadcast
                </button>
              </div>
            </div>
          )}
          <div style={{ height: "4rem", textAlign: "center" }}>
            <a
              style={{ color: "yellow", fontFamily: "monospace" }}
              href="https://docs.1satordinals.com"
            >
              Read the Docs
            </a>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
